spring:
  data:
    mongodb:
      authentication-database: admin
      database: test
      host: 127.0.0.1
      port: 27017
      username: user1
      password: user1

line.bot:
  channel-token: '6OcSwUg5J18lXWngLzlSZgra/Nwfc27aBgNaaBaWlLSOKaouC3un46Iqk5hPL0tCm6aZGnE3J2clBezZ/T7/gL1Aa0vh4OrRT6FTxhNhFX9ewc7SSWU5qBpbufH+9q1/gKB67FwSzji6eZpcNqiUdgdB04t89/1O/w1cDnyilFU='
  channel-secret: '572c7e5ed0a37d4d1d252c2a25a90735'
  handler.path: /callback

# To remove Client wire logs. Please comment out following lines.
# See: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html
#
#logging.level:
#   com.linecorp.bot.client.wire: INFO

